[package]
name = "datanexus-utils"
authors = ["Andrew Fraser<andrew@synchrony-labs.io>"]
version = "0.1.0"
edition = "2018"

[dependencies]
solana-sdk = "1.7.8"
datanexus = { version="0.1.0", path="../program" }
